## Numpy Array & Basics

In [3]:
import numpy as np

### Creating array from list

In [6]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:", arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


### List VS Numpy Array

In [10]:
py_list = [1,2,3]
print("Python list multiplication: ", py_list * 2)

np_array = np.array([1,2,3]) # Element wise multiplication
print("Python array multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

 List operation time:  0.07588362693786621

 Numpy operation time:  0.014169692993164062


### Creating array from scratch

In [16]:
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)

ones = np.ones((2,3))
print("Ones array: \n", ones)

full = np.full((2,2), 7)
print("Full array: \n", full)

random = np.random.random((2,3))
print("Random array: \n", random)

sequence = np.arange(0, 10, 2)
print("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.41792697 0.1399982  0.81117195]
 [0.08286438 0.21601929 0.27720663]]
Sequence array: 
 [0 2 4 6 8]


### Vector, Matrix & Tensor

In [20]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2,3],[4,5,6]],
                   [[7,8,9],[10,11,12]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Array properties

In [23]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape: ", arr.shape) # Rows & Columns
print("Dimension: ", arr.ndim)
print("Size: ", arr.size) # Total numbers of elements
print("Data Type: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


### Array Reshaping

In [30]:
arr = np.arange(12)
print("Original array: ",arr)

reshape = arr.reshape((3,4))
print("\n Reshape array: ", reshape)

flattened = reshape.flatten()
print("\n Flattened array: ", flattened)

# ravel (returns view, instead of copy)
raveled = reshape.ravel()
print("\n Raveled array: ", raveled)

# Transpose (reshape's 3,4 change to 4,3)
transpose = reshape.T
print("\n Transposed array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshape array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
